#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

cd actions/fe-staging-notification

# Run tests for changed files
npx lint-staged

# Ensure build is up to date
npm run build

# Check if dist/index.js changed and needs to be staged
if git diff --name-only | grep -q "actions/fe-staging-notification/dist/index.js"; then
  echo "dist/index.js was updated, staging it..."
  git add actions/fe-staging-notification/dist/index.js
fi
