name: "Production Deployment Notification"
description: "Sends Slack notifications for production deployments with release notes"
inputs:
  webhook-url:
    description: "Slack webhook URL for notifications"
    required: true
  project-name:
    description: "Name of the project being deployed"
    required: true
  release-notes:
    description: "Release notes or commit information"
    required: true

runs:
  using: "node20"
  main: "dist/index.js"
