name: "Production Deployment Notification"
description: "Sends Slack notifications for production deployments with release notes"
inputs:
  webhook-url:
    description: "Slack webhook URL for notifications"
    required: true
  project-name:
    description: "Name of the project being deployed"
    required: true
  release-notes:
    description: "Release notes or commit information"
    required: true

runs:
  using: "composite"
  steps:
    - name: "Notify Slack"
      id: notify_slack
      shell: bash
      run: |
        # Convert GitHub markdown links to Slack format
        # First remove trailing PR links like [#2239](https://github.com/...)
        # Then convert [short-hash](URL) - commit message to short-hash: commit message format
        # Finally add Slack link format to just the short hash
        SLACK_FORMATTED_NOTES=$(echo "${{ inputs.release-notes }}" | \
          sed -E 's/ in \[#[0-9]+\]\([^)]+\)$//g' | \
          sed -E 's/\[([^]]+)\]\(([^)]+)\) - (.+)/\1: \3/g' | \
          sed -E 's/([a-f0-9]{7,}):/<https:\/\/github.com\/InjectiveLabs\/injective-helix\/commit\/\1|\1>:/g')

        # Determine if this is a deployment with new commits or a rebuild
        if [ "${{ inputs.release-notes }}" != "No new commits" ]; then
          # Deployment with new commits
          payload='{
            "text": "'"<!here> 🚀 ${{ inputs.project-name }} deployed to Mainnet!\nView the deployment results on Github: <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}>.\nThe commits deployed are:\n$SLACK_FORMATTED_NOTES"'",
            "attachments": [
              {
                "text": "${{ inputs.project-name }} deployed to Mainnet ✅",
                "color": "#22bb33"
              }
            ]
          }'
        else
          # Rebuild without new commits
          payload='{
            "text": "'"<!here> 🚀 ${{ inputs.project-name }} Rebuilt on Mainnet! Good guys, close your eyes! 🛠️😄"'",
            "attachments": [
              {
                "text": "View the deployment results on Github: <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}>.",
                "color": "#22bb33"
              }
            ]
          }'
        fi

        # Send the notification
        curl -X POST -H 'Content-type: application/json' --data "${payload}" "${{ inputs.webhook-url }}"
