name: "Generate GitHub Release Notes"
description: "Generate GitHub release notes from git commits"

inputs:
  previous_tag:
    description: "The previous tag to compare against"
    required: true
  repo_url:
    description: "The URL of the repository"
    required: true
  branch:
    description: "The branch to generate release notes from"
    required: false
    default: "master"

outputs:
  new_version:
    description: "Incremented github tag number"
  release_notes:
    description: "Generated release notes from git commits"
  bugsnag_version:
    description: "The app version to use for Bugsnag"

runs:
  using: "node20"
  main: "dist/index.js"
