name: "Deployment Notification"
description: "Extract Jira tickets and send Slack notifications for deployments"

inputs:
  repo:
    description: "Repository name (e.g., Mito, Injective)"
    required: true
  network:
    description: "Network name for the deployment"
    required: true
  branch:
    description: "Branch name being deployed (optional - auto-detected from workflow_dispatch input)"
    required: false
  description:
    description: "Description of the deployment"
    required: false
    default: "Frontend deployment"
  slack-user-token:
    description: "Slack user token for reading messages"
    required: true
  slack-bot-token:
    description: "Slack bot token for sending messages"
    required: true
  staging_url:
    description: "URL of the staging deployment"
    required: true
  slack-channel:
    description: "Slack channel name for notifications"
    required: false
    default: "frontend-staging"

outputs:
  branch_name:
    description: "The branch name that was deployed"
  jira_tickets:
    description: "Comma-separated list of Jira tickets found"
  jira_links:
    description: "Formatted Jira links for Slack"
  message_found:
    description: "Whether an existing Slack message was found"
  existing_message_ts:
    description: "Timestamp of existing Slack message if found"
  existing_channel_id:
    description: "Channel ID of existing Slack message if found"
  existing_jira_tickets:
    description: "Jira tickets from existing Slack message"
  channel_name:
    description: "Slack channel name used"
  message_ts:
    description: "Timestamp of the Slack message (either existing or newly created)"

runs:
  using: "node20"
  main: "dist/index.js"
